src/objects/Agile_Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Hrs__c</fullName>
        <label>Estimated Hrs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Remaining_Hrs__c</fullName>
        <label>Remaining Hrs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>Story__r.Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sprint</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Agile Tasks</relationshipLabel>
        <relationshipName>Agile_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Agile Task</label>
    <nameField>
        <displayFormat>AT{0000}</displayFormat>
        <label>Agile Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agile Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sprint__c.object
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StoryID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Temporary reference to external story backlog.</inlineHelpText>
        <label>Story ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StoryPointsAllocation__c</fullName>
        <inlineHelpText>The initial points estimate for this story.</inlineHelpText>
        <label>Story Points Allocation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Story</label>
    <nameField>
        <label>Story  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgileTaskTriggerTest.cls
/*
	Copyright 2012 FinancialForce.com.

	This file is part of SprintWall.

	SprintWall is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	SprintWall is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with SprintWall.  If not, see <http://www.gnu.org/licenses/>.
*/

@isTest
private class AgileTaskTriggerTest 
{
	static testMethod void TestAgileTaskTrigger()
	{
		Team__c team = new Team__c( Name = 'JDHGSAJDHGASJDHG' );
		insert team;
		
		Sprint__c sprint = new Sprint__c( Name = 'KASJDKJSDHKAJDH' );
		insert sprint;
		
		List<Story__c> stories = new List<Story__c>{ 
			new Story__c( 
				StoryID__c = 123456788,
				Sprint__c = sprint.Id,
				Team__c = team.Id,
				StoryPointsAllocation__c = 10,
				Name = 'ASDAS Test Story 1' ),
			new Story__c( 
				StoryID__c = 123456789,
				Sprint__c = sprint.Id,
				Team__c = team.Id,
				StoryPointsAllocation__c = 20,
				Name = 'ASDAS Test Story 2' )
		};
			
		insert stories;
		
		Agile_Task__c task = new Agile_Task__c(
			Title__c = 'My Test Task',
			Description__c = 'This is a test description',
			Story__c = stories[0].Id );
			
		insert task;
		
		task.Estimated_Hrs__c = 10;
		task.Remaining_Hrs__c = 10;
		update task;
		
		task.Estimated_Hrs__c = 20;
		task.Remaining_Hrs__c = 20;
		update task;
	}
}