src/objects/Agile_Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Hrs__c</fullName>
        <label>Estimated Hrs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Remaining_Hrs__c</fullName>
        <label>Remaining Hrs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>Story__r.Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sprint</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Agile Tasks</relationshipLabel>
        <relationshipName>Agile_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Agile Task</label>
    <nameField>
        <displayFormat>AT{0000}</displayFormat>
        <label>Agile Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agile Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sprint__c.object
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StoryID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>Temporary reference to external story backlog.</inlineHelpText>
        <label>Story ID</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StoryPointsAllocation__c</fullName>
        <inlineHelpText>The initial points estimate for this story.</inlineHelpText>
        <label>Story Points Allocation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Story</label>
    <nameField>
        <label>Story  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SprintControllerTests.cls
/*
	Copyright 2012 FinancialForce.com.

	This file is part of SprintWall.

	SprintWall is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	SprintWall is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with SprintWall.  If not, see <http://www.gnu.org/licenses/>.
*/

@isTest
private class SprintControllerTests 
{
	static testMethod void TestSprintWallController1()
	{
		List<sObject> testStories = setupTestData();
		
		Schema.SObjectType taskType = Schema.getGlobalDescribe().get( 'Agile_Task__c' );
        sObject task = taskType.newSObject();
		
		task.put( 'Title__c', 'My Test Task' );
		task.put( 'Description__c', 'This is a test description' );
		task.put( 'Story__c', testStories[0].Id );
			
		insert task;
		
		Test.startTest();
		
		List<AgileTaskHelper.Sprint> sprints = SprintWallController.getSprints();
		system.assert( sprints.size() > 0 );
		
		AgileTaskHelper.Sprint sprint = SprintWallController.getSprint( (Id)testStories[0].get( 'Sprint__c' ), 'Loading...', 'Loading...', 'All' );
		
		String taskId = SprintWallController.changeTaskStatus( task.Id, 'Blocked' );
		sObject task1 = database.query( 'Select Id,Status__c from Agile_Task__c where Id = :taskId' );
		system.assert( (String)task1.get( 'Status__c' ) == 'Blocked' );
		
		taskId = SprintWallController.changeTaskStatus( task.Id, 'In Progress' );
		sObject task2 = database.query( 'Select Id,Status__c from Agile_Task__c where Id = :taskId' );
		system.assert( (String)task2.get( 'Status__c' ) == 'In Progress' );
		
		AgileTaskHelper.AgileTask aTask = SprintWallController.getTaskForEdit( task.Id );
		
		aTask.Description = 'Hello kitty';
		SprintWallController.updateTask( aTask );
		sObject task3 = database.query( 'Select Id,Description__c from Agile_Task__c where Id = :taskId' );
		system.assert( (String)task3.get( 'Description__c' ) == 'Hello kitty' );
		
		List<AgileTaskHelper.Person> people = SprintWallController.getPeople();
		system.assert( people.size() > 0 );
		
		Test.stopTest();
	}
	
	static testMethod void TestSprintWallController2()
	{
		List<sObject> testStories = setupTestData();
		
		Schema.SObjectType taskType = Schema.getGlobalDescribe().get( 'Agile_Task__c' );
        sObject t1 = taskType.newSObject();
        sObject t2 = taskType.newSObject();
        
        t1.put( 'Title__c', 'My Test Task' );
		t1.put( 'Description__c', 'This is a test description' );
		t1.put( 'Story__c', testStories[0].Id );
		
		t2.put( 'Title__c', 'My Test Task' );
		t2.put( 'Description__c', 'This is a test description' );
		t2.put( 'Story__c', testStories[0].Id );
		
		insert t1;
		insert t2;
			
		Id t1Id = t1.Id;
		sObject task = database.query( 'Select Id,Name,Title__c,Description__c,Story__c,Version__c from Agile_Task__c where Id = :t1Id ');
		AgileTaskHelper.Sprint sprint = SprintWallController.getSprint( (Id)testStories[0].get( 'Sprint__c' ), 'Loading...', 'Loading...', 'All' );
			
		Test.startTest();
		
		List<AgileTaskHelper.Team> teams = SprintWallController.getTeams();
		system.assert( teams.size() > 0 );
		
		AgileTaskHelper.StorySummary summary = new AgileTaskHelper.StorySummary();
		summary.Id = testStories[0].Id;
		summary.Tasks = new List<AgileTaskHelper.TaskSummary>();
		
		AgileTaskHelper.TaskSummary taskSum1 = new AgileTaskHelper.TaskSummary();
		taskSum1.Id = task.Id;
		taskSum1.Version = string.valueOf( (Decimal)task.get( 'Version__c' ) );
		summary.Tasks.add( taskSum1 );
		
		List<AgileTaskHelper.AgileTask> changes = SprintWallController.getChanges( 
			'all', 
			'All', 
			new List<AgileTaskHelper.StorySummary> { summary } );
			
		system.assert( changes.size() > 0 );
		
		Test.stopTest();
	}
	
	static testMethod void TestAgileTaskHandler()
	{
		List<sObject> stories = setupTestData();
		
		Schema.SObjectType taskType = Schema.getGlobalDescribe().get( 'Agile_Task__c' );
        sObject task = taskType.newSObject();
		
		task.put( 'Title__c', 'My Test Task' );
		task.put( 'Description__c', 'This is a test description' );
		task.put( 'Story__c', stories[0].Id );
			
		insert task;
		
		task.put( 'Estimated_Hrs__c', 10 );
		task.put( 'Remaining_Hrs__c', 10 );
		update task;
		
		task.put( 'Estimated_Hrs__c', 20 );
		task.put( 'Remaining_Hrs__c', 20 );
		update task;
	}
	
	private static List<sObject> setupTestData()
	{
		Schema.SObjectType teamType = Schema.getGlobalDescribe().get( 'Team__c' );
        sObject team = teamType.newSObject();
        
        team.put( 'Name', 'JDHGSAJDHGASJDHG' );
		insert team;
		
		Schema.SObjectType sprintType = Schema.getGlobalDescribe().get( 'Sprint__c' );
        sObject sprint = sprintType.newSObject();
        sprint.put( 'Name', 'KASJDKJSDHKAJDH' );
		insert sprint;
		
		Schema.SObjectType storyType = Schema.getGlobalDescribe().get( 'Story__C' );
        sObject story1 = storyType.newSObject();
        sObject story2 = storyType.newSObject();
        
        story1.put( 'StoryID__c', 123456788 );
		story1.put( 'Sprint__c', sprint.Id );
		story1.put( 'Team__c', team.Id );
		story1.put( 'StoryPointsAllocation__c', 10 );
		story1.put( 'Name', 'ASDAS Test Story 1' );
		
		story2.put( 'StoryID__c', 123456789 );
		story2.put( 'Sprint__c', sprint.Id );
		story2.put( 'Team__c', team.Id );
		story2.put( 'StoryPointsAllocation__c', 20 );
		story2.put( 'Name', 'ASDAS Test Story 2' );
		
		List<sObject> stories = new List<sObject>{ story1, story2 };
		insert stories;
		
		Set<Id> storyIds = new Set<Id>();
		for( sObject story : stories )
		{
			storyIds.add( story.Id );
		}
		
		// query back for the stories with their respective lookups
		return database.query( 
			'Select ' +
			'	Id, ' +
			'	Name, ' +
			'	Sprint__c, ' +
			'	Team__c ' +
			'From ' +
			'	Story__c ' +
			'Where ' +
			'	Id in :storyIds' );
	}
}