src/objects/Agile_Task__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bug</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Estimated_Hrs__c</fullName>
        <label>Estimated Hrs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <formula>Owner__r.FirstName &amp; &apos; &apos; &amp;  Owner__r.LastName</formula>
        <label>Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Agile_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>P1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Remaining_Hrs__c</fullName>
        <label>Remaining Hrs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <formula>Story__r.Sprint__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sprint</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blocked</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story_Status__c</fullName>
        <formula>TEXT(Story__r.Story_Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Story Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Story</label>
        <referenceTo>Story__c</referenceTo>
        <relationshipLabel>Agile Tasks</relationshipLabel>
        <relationshipName>Agile_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Version</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Agile Task</label>
    <nameField>
        <displayFormat>AT{0000}</displayFormat>
        <label>Agile Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agile Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sprint__c.object
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Story__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StoryPointsAllocation__c</fullName>
        <inlineHelpText>The initial points estimate for this story.</inlineHelpText>
        <label>Story Points Allocation</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Story_Number__c</fullName>
        <displayFormat>{0}</displayFormat>
        <label>Story Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Story_Status__c</fullName>
        <label>Story Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Estimate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ThemePriority__c</fullName>
        <label>Theme Priority</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Theme</label>
        <referenceTo>Theme__c</referenceTo>
        <relationshipLabel>Stories</relationshipLabel>
        <relationshipName>Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Story</label>
    <nameField>
        <label>Story  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Theme__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Theme</label>
    <nameField>
        <label>Theme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Themes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AgileTaskMapper.cls
/*
	Copyright 2012 FinancialForce.com.

	This file is part of SprintWall.

	SprintWall is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	SprintWall is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with SprintWall.  If not, see <http://www.gnu.org/licenses/>.
*/

public with sharing class AgileTaskMapper 
{
	public static List<sObject> getSprints()
	{
		return database.query( 
			'Select ' +
			'	Id, ' +
			'	Name ' +
			'From ' +
			'	Sprint__c ' +
			'Order by Name Desc ' );
	}
	
	public static sObject getTask( Id taskId )
	{
		List<sObject> tasks = database.query(
			'Select ' + 
			getAgileTaskQueryFields() +
			'From ' +
			'	Agile_Task__c ' +
			'Where ' +
			'	Id = :taskId ' );
				
		if( tasks.size() > 0 )
		{
			return tasks[0];
		}
		
		return null;
	}
	
	public static List<sObject> getTasksForStory( Set<Id> storyIds, String ownerId, String categoryName )
	{
		string query = 
			'Select ' +
			getAgileTaskQueryFields() +
			'From ' +
			'	Agile_Task__c ' +
			'Where ' +
			'	Story__c in :storyIds ';
			
		
		if( ownerId != '' && ownerId != null && ownerId != 'all' )
		{
			query += ' and Owner__c = :ownerId';
		}
		if( ownerId == '' || ownerId == null )
		{
			query += ' and Owner__c = null';
		}
		if( categoryName != 'All' && categoryName != '' && categoryName != null )
		{
			query += ' and Category__c = :categoryName';
		}
		if( categoryName == '' || categoryName == null )
		{
			query += ' and Category__c = null';
		}
		
		query +=
			' Order by ' +
			'	Priority__c, Name ASC';
		
		return database.query( query );
	}
	
	public static List<sObject> getStoriesAndTasks( Set<Id> storyIds )
	{
		List<sObject> stories = database.query(
			'Select ' + 
			'	Name, ' + 
			'	Id, ' +
			'	(Select ' +
			 getAgileTaskQueryFields() +
			'	From ' + 
			'		Agile_Tasks__r ' +
			'	Order by ' +
			'		Priority__c, Name ASC) ' + 
			'From ' + 
			'	Story__c where Id in :storyIds' );
			
		return stories; 
	}
	
	public static string getStoryFieldQuery()
	{
		return 
			'	Id, ' + 
			'	Name, ' + 
			'	Description__c, ' +
			'	Story_Number__c, ' +
			'	Team__c, ' +
			'	Team__r.Name, ' +
			'	StoryPointsAllocation__c, ' +
			'	Sprint__c, ' +
			'	Story_Status__c, ' +
			'	Theme__c, ' +
			'	Theme__r.Name, ' +
			'	ThemePriority__c ';
	}
	
	private static string getAgileTaskQueryFields()
	{
		return
			'	Title__c, ' + 
			'	Story__c, ' + 
			'	Status__c, ' + 
			'	Remaining_Hrs__c, ' + 
			'	Priority__c, ' + 
			'	Name, ' + 
			'	Id, ' + 
			'	Estimated_Hrs__c, ' + 
			'	Description__c, ' +
			'	Owner__c, ' +
			'	Owner_Name__c, ' +
			'	Category__c, ' +
			'	Version__c ';
	}
}